import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron"
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  // Support pour les alias de chemin
  plugins: [{
    name: 'alias',
    setup(build) {
      build.onResolve({ filter: /^@\// }, args => {
        const path = args.path.replace(/^@\//, 'src/');
        return { path, namespace: 'file' };
      });
    }
  }]
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}